- name: Install file server packages
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - zfsutils-linux
  - samba
  - smbclient
  - cifs-utils
  - transmission-cli
  tags:
  - packages
