- name: Install basic necessities
  apt: name={{ item }} state=present
  become: yes
  with_items:
  - sshpass
  - python
  - python-pip
  - python3
  - python3-pip
  - curl
  - dnsutils
  - ntp
  tags:
  - packages
