- name: Install basic necessities
  become: yes
  apt:
    name:
    - sshpass
    - python
    - python-pip
    - python3
    - python3-pip
    - curl
    - dnsutils
    - ntp
    state: present
    force_apt_get: yes
- name: Configure .bashrc for globbing
  blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    marker: "# {mark} GLOBBING CONFIG"
    block: |
      set +f
      shopt -s extglob
      shopt -s globstar
- name: Install yq
  become: yes
  pip:
    name: yq
- name: Install pyyaml
  become: yes
  pip:
    name: pyyaml
